{
  imports = [
    ./automount.nix
    ./battmon.nix
    ./bluetooth.nix
    ./communication.nix
    ./cups.nix
    ./displaymanager.nix
    ./firewall.nix
    ./flatpak.nix
    ./fprintd.nix
    ./hyprland.nix
    ./kanata.nix
    ./kdeconnect.nix
    ./nautilus.nix
    ./networkmanager.nix
    ./obs.nix
    ./packages.nix
    ./powersave.nix
    #./razer.nix
    ./sound.nix
    ./steam.nix
    ./virtualization.nix
    ./xdg.nix
    ./yubikey.nix
  ];
}
