{
  imports = [
    ./cmp.nix
    ./dap.nix
    ./lsp.nix
    ./nix.nix
    ./barbar.nix
    ./lualine.nix
    ./neo-tree.nix
    ./telescope.nix
    ./alpha.nix
    ./treesitter.nix
    ./gitsigns.nix
    ./none-ls.nix
    ./lsp-format.nix
    ./floaterm.nix
    ./web-devicons.nix
  ];
}
