# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:

{
  imports = [ (modulesPath + "/installer/scan/not-detected.nix") ];

  boot.initrd.availableKernelModules = [
    "xhci_pci"
    "thunderbolt"
    "vmd"
    "nvme"
    "usb_storage"
    "sd_mod"
  ];
  boot.initrd.kernelModules = [ ];
  boot.supportedFileSystems = [ "nfs" ];
  boot.kernelPackages = pkgs.linuxPackages_latest; # Linux Kernel Version

  boot.kernelParams = [
    "mem_sleep_default=s2idle" # Deep Sleep and nvidia don't work well together
    "i915.force_probe=a7a0" # Use iGPU on startup
  ];

  boot.kernelModules = [
    "kvm-intel"
    "xhci_hcd"
  ];
  boot.extraModulePackages = [ ];

  boot.blacklistedKernelModules = [
    "nouveau"
  ];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/2fde8feb-807d-4d7d-9ad0-1a3798f44df1";
    fsType = "btrfs";
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/12CE-A600";
    fsType = "vfat";
    options = [
      "fmask=0022"
      "dmask=0022"
    ];
  };

  swapDevices = [ { device = "/dev/disk/by-uuid/aec4720d-325d-4792-bd38-4614b6cf82b7"; } ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp44s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlo1.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
