{
  imports = [
    ./automount.nix
    ./bootloader.nix
    ./sound.nix
    ./env.nix
    ./user.nix
    ./displaymanager.nix
    ./networkmanager.nix
    ./steam.nix
    ./hyprland.nix
    ./bluetooth.nix
    ./gpu.nix
    ./cups.nix
    ./nixvim/base.nix
    ./xdg.nix
    ./locate.nix
    ./nh.nix
    ./firewall.nix
    ./suspend-and-hibernate.nix
    ./fprintd.nix
    ./open-vpn.nix
  ];
}
