name: Check

on:
  pull_request:
  push:
    branches: [main]

jobs:
  eval:
    name: Eval flake (hosts, packages, hydraJobs, lockfile)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - run: nix flake check --no-build

  hosts:
    name: Eval host configurations
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        host: [eldraine, kaldheim, kamigawa, theros]
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - run: nix eval --raw ".#nixosConfigurations.${{ matrix.host }}.config.system.build.toplevel.drvPath"

  homes:
    name: Eval home configurations
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - run: nix eval --raw '.#homeConfigurations."voidwalker@kamigawa".activationPackage.drvPath'
      - run: nix eval --raw '.#homeConfigurations."voidwalker@theros".activationPackage.drvPath'
      - run: nix eval --raw '.#homeConfigurations."voidwalker@kaldheim".activationPackage.drvPath'

  format:
    name: Check formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - run: nix fmt -- --ci
